
volumes:
  db-data:


services:

  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  nginx-service:
    build: ./docker/nginx
    container_name: nginx-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/symfony:cached
      - ./var/log:/var/www/symfony/var/log
    depends_on:
      - php
      - database

  php:
    build: ./docker/php
    ports:
      - "${PHP_PORT}:9000"
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/var/www/symfony:cached
