services:

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    container_name: nginx
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx.env
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    volumes:
      - nginx_secrets:/etc/letsencrypt
