
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elastic
    restart: always
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - "9300:9300"
    networks:
      - es-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    restart: always
    ports:
      - "5140:5140/udp"
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - es-network
    depends_on:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - elastic

volumes:
  elasticsearch_data:
    driver: local

networks:
  es-network:
    driver: bridge
