version: '3.8'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox
    links:
      - hub
  chrome:
    image: selenium/node-chrome
    links:
      - hub
