name: Docker Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Dockerfile'
      - '**/Dockerfile*'
      - '**/Dockerfile.*'
      - 'docker-compose*.yml'
      - 'compose.yml'
      - '**/*.sh'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lint Dockerfile using Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: .
          framework: dockerfile
          quiet: true
          container_user: 1000
          skip_check: CKV_DOCKER_2,CKV_DOCKER_3

      - name: Build an image from Dockerfile
        run: docker build -t docker.io/victorysokolov/django-blog:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'docker.io/victorysokolov/django-blog:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
